HCL-TECH-SOFTWARE/domino-rest-adminclient

.github/workflows/pr_check.yml
.github/workflows/publish.yml
localbuild.cmd
localbuild.sh
package-lock.json
package.json
pom.xml

- Simplified pom.xml
- local build scripts
- github actions

Deploy to Github packages

---

src/components/forms/EditView.tsx

- [Regex fix](https://github.com/HCL-TECH-SOFTWARE/domino-rest-adminclient/issues/19)
- [regular expression](https://github.com/HCL-TECH-SOFTWARE/domino-rest-adminclient/issues/20)
- Reduce special characters specified in the regex, instead of a range of characters, which created the warning/alert "Overly permissive regular expression range."

Update regex to specify special characters instead of range

---

src/store/databases/reducer.ts
src/store/databases/types.ts

- N/A
- Fix TS error shown when compiling.

Fix TypeScript errors

---

jar/config/config.json
package.json

- Improve CSP on config.json inside the admin-ui that has a default of "default-src unsafe-inline"
- Added INLINE_RUNTIME_CHUNK=false in the build script in package.json

Tighten CSP

---

package-lock.json
package.json
src/store/applications/reducer.ts
src/store/databases/reducer.ts
src/store/groups/reducer.ts
src/store/index.ts
src/store/people/reducer.ts
src/store/peopleSelector/reducer.ts

Mxop 6680 adminui dependency upgrades

---

package-lock.json
package.json
pom.xml

version bump after dependency updates

---

.github/workflows/push-snapshot.yml

- Mend server pointing to wrong host

Change mend server

---

.github/workflows/push-snapshot.yml

- $PRODUCT_NAME not expanding, try ${{ env.PRODUCT_NAME }}

Rwilkins108 patch 1

---

.github/workflows/push-snapshot.yml
admin-wss.config

Update wss config file

---

admin-wss.config

ignore the test js mocha in whitesource

---

package-lock.json
package.json
pom.xml

Release 1.29.2

---

package-lock.json
package.json
pom.xml

Version bump

---

src/components/database/AddImportDialog.tsx

Do not merge until after release
- Import Schema seems to no longer work
- Fixed behavior of edit schema dialog not showing when importing a schema that has an already existing schema name.
- Updated form validation for editing schema, to show error message when schema name already exists.
- If the schema name exists in the NSF, the schema cannot be saved.

Show import dialog and improve form validation

---

src/components/access/functions.ts
src/store/databases/action.ts

Fix date field type

---

package-lock.json
package.json
pom.xml

- Update version information for upcoming DRAPI v1.0.11 release.

Update version for drapi v1.0.11 release

---

package-lock.json
package.json
pom.xml

DRAPI v1.0.12 release

---

src/components/applications/AppItem.tsx
src/components/applications/AppsTable.tsx
src/components/applications/kanban/Kanban.tsx
src/components/webcomponents/app-status.js
src/components/webcomponents/copyable-text.js
src/custom-elements.d.ts
src/store/applications/action.ts

- Update design for Application Management page
- Changed Application Management page design to be a table, with app name search bar and sorting.
- Used native web components for two simple elements.

[do not merge] Feature/mxop 9745 app page design

---

src/components/applications/kanban/Consents.tsx

remove back button on consents

---

package-lock.json
package.json
src/App.tsx

change router basename

---

package.json
src/App.tsx

- Set Router basename to `/admin/ui`.
- Removed setting of `window.location` in *App.tsx*.
- Changed `homepage` in *package.json* from `..` to `.`.

Fix homepage and basename, fix paths to static assets

---

src/components/applications/AppItem.tsx
src/components/applications/AppsTable.tsx
src/store/applications/action.ts

Mxop 12434 fix app secret behaviour

---

src/components/applications/kanban/Consents.tsx

Revert back close button on application oauth consents

---

src/components/applications/kanban/ConsentItem.tsx
src/components/applications/kanban/Consents.tsx
src/store/consents/action.ts
src/store/consents/reducer.ts
src/store/consents/types.ts

- [MXOP-12432](https://jira01.hclpnp.com/browse/MXOP-12432)
- Remove UNID in remove consent dialog
- Change UNID to username, scope and application name
- The redux for toggleDeleteDialog has refactored to accept username, scope and appName from reactjs global state.

updated revoke consent dialogue

---

package-lock.json
package.json
pom.xml

- DRAPI v1.0.14 release (v1.31.0)

DRAPI v1.0.14 release (v1.31.0)

---

package-lock.json
package.json
pom.xml

Rebuild release v1.0.14

---

src/Views.tsx

- [MXPOP-31925](https://github.com/HCL-TECH-SOFTWARE/domino-rest-adminclient/issues/31925)
- Arrange path components from / root path to subpaths

fix and arrange link hierarchy from root up to sub paths

---

pom.xml

Reduce Maven version in pom b/c 3.9.6 not installed

---

jar/config/config.json
pom.xml

- updated config files based on vite update
- Jar still contains the **\admin** directory, it is not needed but wasn't able to exclude it.  Still needs to be resolved.
- login page doesn't display the keep castle background even though it is found, needs to be resolved.

update config so web works

---

jar/config/config.json

- update router to point to the /img directory

Update image route

---

jar/config/config.json

fix a router mixup

---

jar/config/config.json
pom.xml
vite.config.mts

- move the assets and img directories to the admin directory and update pom file

move assets and img to admin directory

---

index.html

- Shoelace icons not loading
- Update CSP `style-src` and `img-src` to allow assets from the Shoelace CDN.

Update CSP for style-src and img-src

---

package-lock.json
package.json
pom.xml

Update build version number to 1.33.3

---

src/components/lit-elements/lit-source-header.js
src/components/lit-elements/lit-source.js

- Move shoelace icons to local resources
- Add `/admin` to path for local Shoelace icons.

Update paths for local Shoelace icons

---

src/components/schemas/NsfCard.tsx

- Searching a scope in the Scopes NSF View is buggy.
- Corrected `<NsfCard />` to properly select `schemaName` or `apiName` when used.

Add appropriate condition for searching item in NSF card

---

package-lock.json
package.json
pom.xml

- Build Admin UI for DRAPI v1.1 (1.35.0)

V1.1 build (v1.35.0)

---

package-lock.json
package.json
pom.xml

V1.1 (v1.35.1)

---

package-lock.json
package.json
pom.xml

V1.1 (v1.35.2)

---

public/index.html
src/config.dev.ts

- Replaced all instances of `/admin/monaco-editor-core` with just `/monaco-editor-core`.

Replace /admin/monaco-editor-core with just /monaco-editor-core

---

jar/config/config.json

- point monaco-editor-core url to the correct directory in the jar.

point monaco-editor-core url to the correct directory in the jar.

---

src/components/login/LoginPage.tsx

- Username field not changing after an account with a passkey is set.
- Modified `onChange` prop for the Username `<TextField>`.

Handle username change properly

---

src/components/login/LoginPage.tsx

- Set form username to the proper username.

Fix username not being set properly when using passkey login

---

package-lock.json
package.json
pom.xml

DRAPI v1.1.1 release

---

src/components/access/FieldContainer.tsx
src/components/access/FieldDndContainer.tsx
src/components/access/TabsAccess.tsx
src/store/databases/types.ts

- [MXOP-16498](https://hclsw-jiracentral.atlassian.net/browse/MXOP-16498)
- Added a "Required?" toggle to add the field in the `required` array in the schema JSON.
- Show in the field list when that field is required.
- Updated the `Mode` type.

Show required in Fields

---

src/components/database/SchemaContentsTree.tsx

- [[AdminUI] Issues when creating a scope.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-22531)
- Take only unique values of schema names under the same NSF, to display in the file tree.

Remove duplicate schema names under the same NSF in the file tree

---

src/components/home/sections/Section.tsx

Use object instead of img for Keep block diagram to show links

---

src/App.test.tsx
src/components/applications/kanban/AppCard.tsx
src/components/forms/EditView.tsx
src/components/forms/FormsContainer.tsx
src/components/groups/Groups.tsx
src/components/login/pkce.js
src/components/people/PeopleCRUD.tsx
src/store/access/action.ts
src/store/account/action.ts
src/store/applications/action.ts
src/store/databases/action.ts
src/store/groups/action.ts
src/store/people/action.ts
src/store/peopleSelector/action.ts
src/utils/api-retry.ts

- Merge refresh token implementation with my PKCE branch

Refresh token

---

README.md

- [[Admin UI] Include in README instructions on adding web components](https://hclsw-jiracentral.atlassian.net/browse/MXOP-12758)

Update README web components section

---

src/components/applications/kanban/Consents.tsx
src/store/consents/action.ts
src/store/consents/reducer.ts
src/store/consents/types.ts

- Found bug where clicking Revoke Consents doesn't work.
- Updated previous changes made to Revoke Consents.

Update revoke consents usage

---

src/components/login/LoginPage.tsx

- Had an extra line that was causing the Keep IdP login buttons to be disabled by default, so I removed that line.

Remove extra line where the display flag is set incorrectly

---

package-lock.json
package.json
pom.xml

Version number 1.37.0 -> 1.38.0

---

package-lock.json
package.json
pom.xml

V1.1.2 build

---

package-lock.json
package.json
pom.xml

Version bump after release version

---

.gitignore
src/components/applications/AppFilterContainer.tsx
src/components/applications/AppForm.tsx
src/components/applications/AppItem.tsx
src/components/applications/AppsTable.tsx
src/components/applications/kanban/AppCard.tsx
src/components/applications/kanban/Kanban.tsx
src/store/applications/action.ts
src/store/applications/types.ts
src/styles/CommonStyles.tsx

- _NA_
- Add "use PKCE" checkbox for application.
- Add visual cue for PKCE applications in application table.
- Update application filters.

Add "use PKCE" checkbox for application

---

src/store/account/action.ts

- Clicking the logout button clears the user token and refresh token even when the API call fails.

Clear user token, refresh token when clicking logout

---

package-lock.json
package.json
pom.xml

- Creating package for customers to be able to download to fix v1.1.2 OIDC AdminUI Refresh Token issue

V1.1.2 OIDC fix

---

src/components/login/LoginPage.tsx

- Logged in using OIDC, then logged out, and only a white screen is displayed.

Fix white screen displayed after logging out using OIDC

---

package-lock.json
package.json
pom.xml

Drapi v1.1.3 release

---

package-lock.json
package.json
pom.xml

Version bump after release

---

package-lock.json
package.json
pom.xml

Release v1.1.3 take2

---

package-lock.json
package.json
pom.xml

V1.1.3 take 3

---

src/components/access/AccessMode.tsx

- [[Admin UI] List of fields added to form doesn't update properly](https://hclsw-jiracentral.atlassian.net/browse/MXOP-28039)
- Removed `setstate` when refreshing the UI for the list of added fields.

Remove unnecessary setstate for list of fields

---

admin-wss.config
index.html

- change mend scan to scan all plugin sources or else won't find vulnerabilities.

change mend to scan sources as well

---

package-lock.json
package.json
pom.xml

Build v1.1.3.1

---

package-lock.json
package.json
pom.xml

Release v1.1.4

---

package-lock.json
package.json

- [[AdminUI] Fix Mend reported Vulnerabilities](https://hclsw-jiracentral.atlassian.net/browse/MXOP-35068)
- Added override for YAML version.

Override yaml version to ^2.6.1
