HCL-TECH-SOFTWARE/domino-rest-adminclient

- src/components/access/FieldDndContainer.tsx
- NA
- Clicking trash icon on the side of a selected field causes error. Removed it since we have another way to delete fields now.
> Remove old delete icon for selected fields

- .github/workflows/push-snapshot.yml
I think setting the product name with underscores had issues, so make a different Mend name for scans.
Unfortunately Github Actions doesn't seem to have string replace function, so create a new env for Mend.
-
> Separate Mend Name from Product Name

- src/components/login/LoginPage.tsx
Do not merge until after release
- if protocol is http (not https) do not show "Sign up with Passkey"
- Added checker to see if protocol is HTTP or HTTPS, and hide passkey option if protocol is HTTP.
> Detect protocol then hide passkey option for HTTP

- src/components/home/sections/Section.tsx
- src/components/routers/BreadcrumbRouter.tsx
- Removed duplicate Application Management Page icon from home page.
- Fixed breadcrumb in Consents.
> Fix Consents breadcrumb and remove duplicate App page in home page

- src/components/forms/EditView.tsx
- Customer issue Japanese Column Titles are not showing up as External names when editing view.
- Changed how `externalName` is being converted from the column title. Fixed RegEx used.
> Fix regex that converts column title or name to external name

- src/components/forms/ActivateMenu.tsx
- src/components/forms/FormsTable.tsx
- src/store/databases/action.ts
- [Admin UI] In Forms, click Edit to activate then go to page
- Added a `successCallback` parameter in the `handleDatabaseForms` action. This will be called whenever the user tries to edit an inactive form, so that once the form has been activated, Admin UI will automatically redirect the user to that form editor.
> Add handling for clicking edit on inactive form

- src/components/forms/ActivateMenu.tsx
- src/components/forms/FormsTable.tsx
- src/store/databases/action.ts
- Clicking Form Activate button works differently then activating with the pencil button.
- Replaced function used in the 3-dot menu to be the same one that is used in clicking the edit icon, so that aliases will be correct.
> Replace function to activate form in 3-dot menu

- src/components/access/Fields.tsx
- Bug found in Forms when searching nonexistent field
- Updated the part where form fields are filtered, to handle filtering when the search string does not match any field.
> Fix filtering in fields when search key doesn't match any field

- src/components/sidenav/SideNav.tsx
- In side bar, both Applications and Consents are highlighted when viewing Consents.
- Added correct condition for setting the class name, which includes the "highlighted" effect/background color..
> Set correct condition for class to highlight navlink

- src/components/login/LoginPage.tsx
- Issue with castle background in login page not showing.
- Removed the `item` and sizing props in the `<Grid />` component that was using the castle background image.
> Do not use Grid item for Castle background

- jar/config/config.json
- Address this issue when loading the Source tab: _Refused to connect to 'https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/assets/icons/plus-circle.svg' because it violates the document's Content Security Policy._
- Updated CSP `img-src` to include Shoelace assets.
> Add Shoelace assets to CSP img-src

- src/components/forms/FormsContainer.tsx
- src/components/lit-elements/LitElements.tsx
- src/components/lit-elements/lit-source-header.js
- src/components/lit-elements/lit-source.js
- Implement Source tab header
- Changed header style.
- Changed "styled object" to "tree view".
- Changed switcher from toggle pill style to dropdown.
- Added buttons to copy JSON, or to download it into a file called _schema.json_.
> Add new style for header of Source tab

- index.html
- jar/config/config.json
- Shoelace icons not loading
- Based on the console errors seen in Frascati, it seems that the CSP directives being followed are the ones in _config.json_, so I updated that instead.
> Update and move CSP to config.json

- src/components/access/Fields.tsx
- src/components/home/sections/Section.tsx
- src/components/sidenav/MobileSidebar.tsx
- src/styles/CommonStyles.tsx
- When logging in via iPhone or Android phone, only a blank screen is shown.
- Changed `theme.palette.mode` which is Material UI v4 syntax.
> Remove Material UI v4 theme usage

- public/img/shoelace/dash-square.svg
- public/img/shoelace/plus-square.svg
- src/components/lit-elements/lit-source-header.js
- src/components/lit-elements/lit-source.js
Should be able to see these icons on the left:
> Add missing icons for expand/collapse of Source tree

- src/components/sidenav/MobileSidebar.tsx
- src/components/sidenav/SideNav.tsx
- Side nav items placed at the bottom, should put them back on top.
> Reposition side nav items from bottom to top

- src/components/access/ScriptEditor.tsx
- src/components/access/TabsAccess.tsx
- After clicking Add Mode, the mode name text isn't being set properly.
- After editing a Formula, clicking Save doesn't properly update the UI.
- Added `useEffect` to properly set mode name text.
- Added `useEffect` to properly set Formula Editor values after clicking Save.
> Sets the current mode name text properly after adding a mode

- src/components/applications/AppsTable.tsx
- [Admin UI] "Applications loading" is showing even when there are no applications.
- Change the `<APILoadingProgress />` component to the `<ZeroResultsWrapper />` component.
> Change loading text to zero results text when there are no fetched apps

- src/components/lit-elements/lit-source.js
- [AdminUI] Source Tab, cannot add a new object/array to another object.
- Added a missing dialog to objects and arrays in the source tab.
> [Do not merge] Add missing dialog to object item to add items

- src/components/access/SingleFieldContainer.tsx
- src/store/databases/action.ts
- In Field Setting, show the type and kind beside the item name.
`editable`:
`computed`:
`computedfordisplay`:
`computedwhencomposed`:
> Add info icon beside fields to show the kind of the field

- src/components/access/FieldContainer.tsx
- src/components/access/ScriptEditor.tsx
- src/components/access/TabsAccess.tsx
- src/components/access/styles.ts
- Display all Field Settings instead of having to scroll.
Decreased font sizes so that there's no need to scroll in Field Setting and Mode Settings.
> Decrease font sizes in Fields

- src/components/forms/FormsTable.tsx
- src/store/databases/action.ts
- src/utils/common.ts
- Forms with special characters are not being encoded when retrieving the list of fields for the form
- Changed the `fullEncode` function to add the `'` for encoding.
- URLs in the form name will have the encoded form name when opening them.
> Add apostrophe to the fullEncode function

- src/components/access/FieldContainer.tsx
- After clearing the field name using the keyboard, the displayed value in the text field defaults to the old value.
> Handle empty input to field name text field

- src/components/forms/FormsTable.tsx
- src/utils/common.ts
- If a View or Form ends in a # sign, it is dropped from the sending URL
- Added `#` to the `fullEncode` function.
- Replaced `encodeURIComponent` with our custom `fullEncode` for calling the _forms_ API.
> Include pound sign in fullEncode function

- index.html
Fix CSP error when using Monaco Editor package
After checking the Source tab in Frascati, I saw that there was still an error loading _loader.js_ because of a MIME type error.
- Set MIME type to `application/javascript` in _index.html_.
> Resolve MIME type issue for loader.js

- index.html
- src/components/forms/FormsContainer.tsx
- MIME type not executable for Monaco Editor still showing up.
Removed the `<script>` tag I initially added in _index.html_ since another `<script>` tag is being created when the Monaco Editor is first loaded. So instead, I added a `useEffect` in the component that calls on Monaco Editor, to add the attribute `type="application/javascript"` to that added `<script>` tag.
> Override script tag being added to include type="application/javascript"

- public/index.html
Still getting the error `MIME type ('') not executable`.
- Added the `<script>` tag for loader.js in public/index.html.
> Load loader.js script with proper type in public/index.html

- src/components/login/LoginPage.tsx
- 'Clear passkey' option isn't needed - can potentially cause user misunderstanding & UX issue
- Removed "Clear Passkey" option.
- Both "Log In With Passkey" and "Sign Up With Passkey" options are now always shown.
- Replaced "Log In" with "Log In With Password" for more clarity.
> Remove Clear Passkey option and always show all other passkey options

- jar/config/config.json
Warnings coming up in the console when loading the Source text view.
- The warnings were stating a CSP violation, because it was trying to load a blob, so I added `worker-src: 'self' data: blob:` to the CSP declared in _config.json_.
> Update CSP to add worker-src and include blob

- src/components/lit-elements/lit-source.js
- Can only add one item to an array; need to hit Save before adding another item.
- To add to an array, in the background we add it as a key-value pair, where the "key" is the index of the array. But currently, that index isn't changed even when we add multiple items to the array. So, the fix is the update the index whenever we add an item to an array.
> Update key when an item is added to an array

- src/components/forms/FormsContainer.tsx
- src/components/lit-elements/lit-source.js
Found some more issues in the Source tab:
- Removing the children of an array doesn't work.
- Editing a boolean value through the textbox will show an error.
I also saw that the editor.main.js CSP issues were addressed through updating our CSP, but it was showing errors still. I don't think I can fix it right away so I just suppressed the errors for now.
> Resolve Remove and Edit issues in Source tab

- src/components/forms/EditView.tsx
- src/components/lit-elements/lit-source.js
- In the Source tab's tree view, clicking Edit in the Context Menu doesn't show the dialog properly.
- In the Edit View Columns dialog, once you change the external name of a column, and then click Add All to add the remaining columns, the external name gets reset to the original. Changed this so that the external name does not get reset.
> Resolve issues with Source tab tree view and Edit Columns in Schema page

- src/components/database/AddImportDialog.tsx
- src/styles/CommonStyles.tsx
- [MXOP-16500](https://hclsw-jiracentral.atlassian.net/browse/MXOP-16500)
- Removed `fullScreen` in Add Schema dialog to resolve the issue of the dialog being gray on Safari screens.
> Remove fullScreen prop in dialog to resolve gray dialog issue

- src/components/access/ModeCompare.tsx
- src/components/applications/DeleteApplicationDialog.tsx
- src/components/database/AddImportDialog.tsx
- src/components/forms/ActivateMenu.tsx
- src/components/forms/ActivateSwitch.tsx
- src/components/forms/ColumnDetails.tsx
- src/components/forms/DetailsSection.tsx
- src/components/forms/EditView.tsx
- src/components/forms/FormsContainer.tsx
- src/components/forms/TabAgents.tsx
- src/styles/CommonStyles.tsx
- [Scroll bars in DRAPI Admin UI](https://hclsw-jiracentral.atlassian.net/browse/MXOP-21406)
- Mostly set dialogs to have the CSS property `overflow-y: auto` so that when the screen is small, it automatically adds a scrollbar on the side.
- Fixed heights of dialog content to fit inside the dialog.
> Fix scrollbar behavior in affected dialogs

- src/components/lit-elements/LitElements.tsx
- src/components/lit-elements/lit-button-neutral.js
- src/components/lit-elements/lit-dialog-actions.js
- src/components/lit-elements/lit-dialog-content.js
- src/components/lit-elements/lit-dialog-header.js
- src/components/lit-elements/lit-textform-array.js
- src/components/lit-elements/lit-textform.js
- [[AdminUI] Make Validation Dialog look more like other Formula Dialogs](https://hclsw-jiracentral.atlassian.net/browse/MXOP-22677)
- Changed dialog size.
- Changed input style of form.
- Changed how the keys of `validationRules` are displayed in the form: `formulaType` to "Formula Type", `formula` to "Formula", `message` to Error Message.
- Added new Lit elements: dialog header, dialog content, dialog actions -> for reusability in future dialogs.
- Modified background color of our custom Lit "neutral" button to only have background color when hovered.
> Style Add Rule dialog, add dialog elements using Lit

- src/components/access/FieldContainer.tsx
- [[AdminUI] Issues with Schema FieldGroup item.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-22532)
- Added a default value of an empty string for the input component for Field Group.
> Add default value empty string for Field Group input

- src/components/home/sections/Section.tsx
Added the block diagram to the top of the home page.
Currently the width is set at 50%, but can be changed if you'd like.
> Add Keep block diagram to home page

- src/components/access/FieldContainer.tsx
- [[Admin UI] "Field Type" text in Test Formulas](https://hclsw-jiracentral.atlassian.net/browse/MXOP-24667)
- Changed z-index of the Field Type text element to 0 so that it doesn't show up in the Test Formulas drawer.
> Adjust z-index of Field Type in edit field section

- src/components/login/LoginPage.tsx
- src/components/login/pkce.js
- [[Admin UI] Do not read the scope parameter from /auth/idpList response for PKCE login](https://hclsw-jiracentral.atlassian.net/browse/MXOP-25060)
- Removed scope when reading `GET /auth/idpList` response, and as a parameter when initiating authorization request.
> Remove scope from PKCE login flow

- src/components/lit-elements/lit-textform-array.js
- [[Admin UI] Delete Rule dialog box looks off](https://hclsw-jiracentral.atlassian.net/browse/MXOP-25059)
- Added header and body/content section for Delete Rule dialog.
> Update Delete Rule dialog UI

- src/components/login/LoginPage.tsx
- src/config.dev.ts
- src/store/account/action.ts
- [[AdminUI] Enable or Disable ODIC / Keep Login buttons according to setting.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-25108)
- Added `getKeepIdpActive` action to call `keepidp-v1/active` endpoint, and disabled appropriate buttons and fields according to this return value.
- Added `IDP_KEEP_API_URL` macro.
This is what it looks like when the Keep IdP login buttons and fields are disabled:
> Handle keepidp-v1/active endpoint in UI

- src/components/login/pkce.js
- src/utils/api-retry.ts
- After logging in to Admin UI, closing and then reopening it after some time, we couldn't access schemas, scopes, etc.
- Fixed the flow for using the refresh token.
> Change condition for calling refresh and properly parse refresh token

- src/components/access/ScriptEditor.tsx
- [[AdminUI] Formula for Write Access tile should always show Compute with form state.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-26476)
- Show _Compute With Form - enabled_ or _Compute With Form - disabled_.
> Show whether Compute With Form is enabled or disabled

- jar/config/config.json
- [[Admin UI] Tighten CSP, remove unsafe-inline](https://hclsw-jiracentral.atlassian.net/browse/MXOP-26857)
- Removed `unsafe-inline` for `script-src` CSP directive.
- Added `data:` to `connect-src`.
> Remove unsafe-inline for script-src

- src/components/access/AccessMode.tsx
- src/components/access/FieldDndContainer.tsx
- src/components/access/TabsAccess.tsx
- [[Admin UI] Bug when editing field name.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-26842)
- Added `await` statement before `dispatch(updateFormMode)` so that the updates are loaded before the field editor component is reloaded/re-mounted.
- Added state `fieldIndex` to properly show the latest edited field.
> Add state fieldIndex for properly managing the field editor

- src/components/database/SchemaContentsTree.tsx
- [[Admin UI] Expanding a database in scope form doesn't work under different account](https://hclsw-jiracentral.atlassian.net/browse/MXOP-27218)
- Added `idx` (index) to `itemId` for uniqueness (since the error was that Tree Item ID was not unique).
Addressed this error:
> Add index to TreeItem itemId

- src/store/databases/action.ts
- [[Admin UI] Handling error when saving a form.](https://hclsw-jiracentral.atlassian.net/browse/MXOP-28040)
- Set `loading` flag to `false` in error handling.
> Set loading flag to false after API call error

- src/components/lit-elements/LitElements.tsx
- src/components/lit-elements/lit-api-error-dialog.js
- src/components/login/LoginPage.tsx
- src/components/login/pkce.js
- [[Admin UI] initiateAuthorizationRequest error handling](https://hclsw-jiracentral.atlassian.net/browse/MXOP-26848)
- Added dialog to show when an error occurs on OIDC login.
- Added alert when an error occurs when refreshing the access token, which takes the user back to the login screen.
> Add dialog to show PKCE login error

- src/components/access/AccessMode.tsx
- src/components/access/ScriptEditor.tsx
- src/components/access/TabsAccess.tsx
- [[AdminUI] Add Continue On Error toggle as a child of Compute With Form](https://hclsw-jiracentral.atlassian.net/browse/MXOP-28346)
- Added toggle to UI and updated schema.
- Fixed field list update issue.
> Add Continue On Error toggle to Field Editor

- src/components/access/ScriptEditor.tsx
- Expand icon for Validation Rules section not changing when expanded.
- Changed the toggle variable to properly change the expand icon.
> Change toggle variable for expand icon of Validation Rules

- src/components/schemas/SchemasLists.tsx
- src/utils/common.ts
- [[Admin UI] Fix error on schema page, possibly from Lit Schema Card](https://hclsw-jiracentral.atlassian.net/browse/MXOP-31553)
- Added throttling of 250 ms to the `useEffect` that updates the cards to prevent maximum update depth exceeded error.
> Add throttling for schema cards

- src/components/schemas/SchemasLists.tsx
- Only one schema card initially shows up in Frascati.
- The problem occurs most likely due to throttling, so I removed the throttling solution to the initial problem (schema cards not reloading).
- Used incremental updates and removed using the `results` state from `useEffect` to prevent "Maximum update depth exceeded" error.
> Remove throttling, use incremental updates instead

- src/components/applications/AppFilterContainer.tsx
- src/components/applications/AppForm.tsx
- src/components/applications/FormDrawer.tsx
- src/components/database/QuickConfigForm.tsx
- src/components/database/QuickConfigFormContainer.tsx
- src/components/database/ScopeForm.tsx
- src/components/database/ScopeFormContainer.tsx
- src/components/lit-elements/LitElements.tsx
- src/components/lit-elements/lit-drawer.js
- src/styles/CommonStyles.tsx
- [[Admin UI] Convert drawer component to use Lit element](https://hclsw-jiracentral.atlassian.net/browse/MXOP-35692)
- Added Lit drawer.
- Replaced drawer for: Quick Config, Add Scope, Add Application, Application Filter, Consents Filter.
- Adjusted some widths inside the drawers.
> Convert drawer element to use Lit instead of MUI
